# Upac configuration file
# Copy to /etc/upac/config.toml and adjust paths as needed
step_retries = 3
verbose = false

[paths]
# Directory where package metadata is stored
database_path = "/var/db/upac"

# OSTree repo
repo_path   = "/var/repo"

# Root of the filesystem where hardlinks are created
root_path   = "/"

[ostree]
# Branch name used for OStree commits
branch  = "packages"
