# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[package]
name = "upac-types"
description = "Rust-native domain types shared between upac-lib and its direct Rust consumers, independent of the C ABI"
version.workspace = true

edition.workspace = true
rust-version.workspace = true

license.workspace = true

readme.workspace = true
homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

include = ["/src"]

[lints]
workspace = true

[dependencies]
upac-macro = { workspace = true }
upac-abi   = { workspace = true }

serde = { workspace = true }
sha2  = { workspace = true }
toml  = { workspace = true }
